steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/contiunousi/web:$SHORT_SHA','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/contiunousi/web:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'reggie', '--region=asia-east1', '--platform=managed', '--image=gcr.io/contiunousi/web:$SHORT_SHA']
